# https://taskfile.dev/usage/
version: '3' # the version of taskfile being used

tasks:
  clean:
    cmds:
      - rm -f greetings

  build:
    deps: [clean]
    sources:
      - ./*.mod
      - ./*.go
    generates:
      - greetings
    cmds:
      - go version
      - go build -v

  test:
    deps: [build]
    cmds:
      - go test -v

  run:
    deps: [build]
    cmds:
      - go run .